### PR TITLE
Cluster chart version

### LINKED ISSUE #569: Fluvio CLI 0.6.0-alpha.7 doesn't install right version
Steps to reproduce: download Fluvio from installer

Show right version
```
fluvio version
Fluvio CLI      : 0.6.0-alpha.7
Fluvio Platform : Not available
Git Commit      : 70a1423a2c0d22817f9015a5aa88686f1723a66d
OS Details      : Linux 5.4.0-1031-azure x86_64 GNU/Linux
Rustc Version   : 1.48.0 (7eac88a 2020-11-16)
```

Trying to install fluvio

```
fluvio cluster start
"fluvio" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "fluvio" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: 
   0: Failed to install Fluvio on Kubernetes
   1: Unable to find chart in Helm: fluvio/fluvio-app:0.6.0
```

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #569

### CODE REVIEW

File: src/cluster/src/lib.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ pub use check::{ClusterChecker, CheckStatus, CheckStatuses};
 pub use check::{RecoverableCheck, UnrecoverableCheck};
 pub use delete::ClusterUninstaller;
 
-const VERSION: &str = include_str!("VERSION");
+const VERSION: &str = include_str!("../../../VERSION");
```
Comment (sehz) [inline src/cluster/src/lib.rs:41]: need to put this behind feature flag, so it can be published

**Review by sehz — CHANGES_REQUESTED** [review]

**Review by sehz — CHANGES_REQUESTED** [review]
Can you also bump up version as well?

**Review by sehz — APPROVED** [review]

**Comment by sehz** [comment]
smoke test failure due to change in topic creation logic: https://github.com/infinyon/fluvio/issues/589.  re-running CI
