### PR TITLE
OS version at runtime

### LINKED ISSUE #364: OS details for Linux binary is wrong
download [CLI](https://github.com/infinyon/fluvio/releases/download/v0.6.0-alpha.2/fluvio-v0.6.0-alpha.2-x86_64-unknown-linux-musl) for linux.  

```
fluvio version
Fluvio version : 0.6.0-alpha.2
Git Commit     : 9534b85bc34866acf50a13f777ee57ebf43e35fa
OS Details     : Darwin 19.6.0 x86_64
Rustc Version  : 1.46.0 (04488af 2020-08-24)
```

OS details is coming from cross compiler not actual target.

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #364 

This is a CLI-only change that just causes the `fluvio version` command to check OS details at runtime rather than compile time.

### CODE REVIEW

**Comment by sehz** [comment]
What about crate like this? https://crates.io/crates/rsys

**Comment by nicholastmosher** [comment]
That would probably be much better, I'll change the implementation

File: src/cli/src/lib.rs [hunk 1]
```diff
@@ -257,14 +257,34 @@ impl VersionOpt {
...
 
+/// Fetching OS info on non-unix not supported
+#[cfg(not(unix))]
+fn os_info() -> Result<Option<String>> {
+    Ok(None)
+}
+
+/// Fetch OS information if on unix
+#[cfg(unix)]
+fn os_info() -> Result<Option<String>> {
```
Comment (simlay) [inline src/cli/src/lib.rs:276]: How do you feel about using https://crates.io/crates/sysinfo?

**Comment by sehz** [comment]
rebase and resolve conflicts

**Review by sehz — APPROVED** [review]
