### PR TITLE
Cli error printout

### LINKED ISSUE #580: Simplify error message in the CLI
For example, when trying to create duplicate topic;
```
$ fluvio topic create test
Error: 
   0: Consumer Error
   1: Fluvio client error
   2: Fluvio SC schema error
   3: Received error code: TopicAlreadyExists (Some("topic \'test\' already defined"))
```

This is too much information.  We should review and come up with more format

---

This seems to be one of several cases where a somewhat "expected" outcome of running a command should not be rendered as an error. We shouldn't change our general-purpose error-handling mechanism, but rather for the purpose of the `fluvio topic create test` command, we should watch for this specific error and manually render it in a well-defined way.

We should keep an eye out for other commands that exhibit a similar behavior where they are rendering "expected" results as errors, and come up with a uniform way of rendering them nicely.

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #580 

This adds graceful error handling to `fluvio topic create` (if a named topic already exists) and to `fluvio topic delete` (if the named topic does _not_ already exist).

Topic create used to look like this:

```
❯ cargo run --bin fluvio -- topic create foobar
Error:
   0: Consumer Error
   1: Fluvio client error
   2: Fluvio SC schema error
   3: Received error code: TopicAlreadyExists (Some("topic \'foobar\' already defined"))

```

Topic create now looks like:

```
❯ cargo run --bin fluvio -- topic create foobar
topic "foobar" created

❯ cargo run --bin fluvio -- topic create foobar
Topic already exists
```

Topic delete now looks like this:

```
❯ cargo run --bin fluvio -- topic delete foobar
Topic not found
```

One thing I added here is a new error variant: `CliError::ExitWithCode`. It is intended to signal that an error occurred _but was already handled_, and that after execution has bubbled all the way back up to main, it should exit with a particular error code. This is in order to avoid planting `std::process::exit(code)` throughout the codebase.

### CODE REVIEW

**Comment by sehz** [comment]
need to be rebased

File: src/cli/src/lib.rs [hunk 1]
```diff
@@ -229,7 +232,22 @@ impl FluvioCmd {
                 produce.process(&fluvio).await?;
             }
             Self::Topic(topic) => {
-                topic.process(out, &fluvio).await?;
+                let result = topic.process(out, &fluvio).await;
+                match &result {
+                    Err(ConsumerError::ClientError(FluvioError::ApiError(api))) => match api {
```
Comment (sehz) [inline src/cli/src/lib.rs:237]: Why specific custom handling here instead of just printing out error?

**Review by sehz — CHANGES_REQUESTED** [review]

File: src/cli/src/lib.rs (hunk 1 above)
Comment (nicholastmosher) [reply src/cli/src/lib.rs:237]: That was the point of this whole PR. The behavior we want for `fluvio topic create` is:

- If the topic does not already exist, create it and print `topic "X" created`
- If the topic already exists, do nothing, but print `Topic already exists` and return exit code 1

previously, what would happen is that the `TopicAlreadyExists` error would bubble all the way up and get printed as a color_eyre error with the red error stack. Now, that specific error type is handled in our specified way.

Comment (nicholastmosher) [reply src/cli/src/lib.rs:237]: (similarly for `fluvio topic delete`)

Comment (sehz) [reply src/cli/src/lib.rs:237]: Why not update `eyere` format?

Comment (nicholastmosher) [reply src/cli/src/lib.rs:237]: I think that the eyre format is good for what it is intended for. I see it as these are two different cases:

1) When trying to create a topic that already exists, this is a "domain error", something that is well-understood and all we need to do is inform the user what happened.
2) When something unexpected goes wrong, this is a "system error", something that we can consider a bug. When this happens, we want to be presented with as much information as possible so that we can understand where the problem originated. This is where eyre's error stack comes in handy: we can get a summary of where the error originated and a general idea of what went wrong.

Comment (sehz) [reply src/cli/src/lib.rs:237]: This seems too complex for what we need right now.  Let's just display error and reserve stack based rendering for advanced or debug mode.

**Comment by nicholastmosher** [comment]
@sehz I gave this another shot by moving the error display code to `error.rs` so it is no longer handled right in the app logic. Let me know if this looks better to you.

**Comment by sehz** [comment]
What about other errors?  They all should return -1.  Not sure why only topic need to be handle special.  
```
#[derive(Error, Debug)]
pub enum FluvioError {
    #[error("Topic not found: {0}")]
    TopicNotFound(String),
    #[error("Partition not found: {0}-{1}")]
    PartitionNotFound(String, i32),
    #[error("Spu not found: {0}")]
    SPUNotFound(i32),
    #[error(transparent)]
    IoError(#[from] IoError),
    #[error("Fluvio socket error")]
    FlvSocketError(#[from] FlvSocketError),
    #[error("Fluvio SC schema error")]
    ApiError(#[from] ApiError),
    #[error("Fluvio config error")]
    ConfigError(#[from] ConfigError),
    #[error("Attempted to create negative offset: {0}")]
    NegativeOffset(i64),
    #[error("Cluster (with platform version {cluster_version}) is older than the minimum required version {client_minimum_version}")]
    MinimumPlatformVersion {
        cluster_version: Version,
        client_minimum_version: Version,
    },
    #[error("Unknown error: {0}")]
    Other(String),
}
```

**Comment by nicholastmosher** [comment]
The other errors get bubbled up untouched, meaning that `color_eyre` will print them as the typical error stack and return exit code 1, just like we've already been doing.

To your point about "just displaying the error", the reason I'm having a hard time thinking about that is because it seems like that would still not give us a good output either way. Would we print the Display of the most top-level error? Because then we would end up with a message such as "Fluvio Client error", which tells us almost nothing about what happened. But if we print the Display of the lowest-level error, then we could end up with a message such as "file not found (OS error X)", which also does not help the user to know what has happened. To me, the only way to communicate what has actually happened is to either include the context of the entire stack of errors, or to convert that stack of errors into a single statement that describes the situation, which is what I'm trying to do in this PR.

**Comment by sehz** [comment]
There doesn't need to be just one way to display error.  In this case, we should optimize for simple case.  Can add flag or env variable to display detail stack as before like `BACKTRACE` flag for rust binary.   

I also think we need to separate error into separate categories to make it easier to handle in the future.

**Review by sehz — APPROVED** [review]
